_includes/nav-main.html
about.html
contribute.html

Deals with issue #44 as well as issue #43.

Adding more Info to About page

---

about.html
index.html

Includes a number of other fixes such as
* moving to using the svg version of the logo.
* removing extra white spaces.

Updated board membership list

---

_config.yml
_posts/2014-06-26-SunPy-0.5.md
_posts/2015-08-04-SunPy-05.md
_posts/2015-08-04-SunPy-06.md
_posts/2015-09-30-SunPy-061.md
_posts/2015-10-01-Monthly-Update.md
atom.xml
rss.xml

Three blog posts and various tweaks so it builds without warning

---

_posts/2015-11-02-Monthly-Update.md

November update

---

_posts/2016-03-21-python-in-astronomy.md

Anything else that should be mentioned @Cadair?

Blog post for pyastro16

---

_posts/2016-05-26-SunPy-07.md

I couldn't get Jekyll running on my local machine, so could someone test this before merge?

Add a 0.7 blog post

---

about.html

Added info on google calendar

---

contribute.html

Update contribute.html link updated to matrix channel

---

css/bootstrap-theme.css
css/bootstrap-theme.min.css
css/bootstrap.css
css/bootstrap.min.css
js/bootstrap.js
js/bootstrap.min.js

Update bootstrap.css bootstrap version updated

---

_config.yml
_includes/nav-main.html

This should fix that (I think).

Double // in the URLS

---

help.html

help section Docs link updated 

---

_includes/nav-about.html
about.html

I uploaded some on the Sunpy videos and presentation links on the website.
I hope it will be great.
Any improvements that are needed in the design?
@Cadair 
@dpshelio

Sunpy Presentations and Talks Upload on the Site

---

conf.py

needs https://github.com/sunpy/sunpy-sphinx-theme/pull/28

footer conifg stuff

---

conf.py
posts/2018/2018-02-25-ndcube.rst

fix intersphinx links in the ndcube post

---

Makefile
conf.py
requirements.txt
team.rst

Should make interlinks work now. 
Also changed the AFs to the current ones. 
Closes #115
Closes #114
Closes #112

Tidy of a few minor issues

---

requirements.txt

Will need to be reverted eventually if this breaks.

test with current beta version of theme

---

requirements.txt

Revert "test with current beta version of theme"
This reverts commit 60b3b50e9d841ff2f6af7423208e6137df69c635.

Merge this when theme update is pushed. 

---

posts/2018/2018-10-20-time.rst

As I promised. 
Sorry for the delay.
:cake:

Add time blog post

---

.gitignore
about.rst
conf.py

This should probably not be merged until sunpy/sunpy#2934 is in

Download CITATION.rst from SunPy as part of the build

---

posts/2019/2019-05-16-GSoC2019-Project-NDCube-0.rst
posts/2019/2019-05-16-GSoC2019-Project-NDCube-1.rst

Added two blog posts for - 
* Introduction to GSoC
* Community Bonding Period

Added posts for the two weeks of GSoC for community bonding period

---

posts/2019/The Road to GSOC.rst

This is my first blog and not the community bonding period one. I will write it later. It is just to test.

Added my first blog

---

index.rst

Should work now with 1.2.6 of the theme. 
Fixes #155

update for version on front page

---

conf.py

fix for blog rss link

---

posts/2019/2019-06-19-GSoC2019-Project-NDCube-4.rst
posts/2019/2019-06-19-GSoC2019-Project-NDCube-5.rst

Blogposts for `Sunpy` `NDCube`

Added blogposts for week 2 and 3

---

posts/2019/2019-07-08-GSoC2019-Project-NDCube-6.rst
posts/2019/2019-07-08-GSoC2019-Project-NDCube-7.rst
posts/2019/2019-07-08-GSoC2019-Project-NDCube-8.rst

Added 3 blog-posts for week 4, 5 and 6.

Added 3 blog-posts for week 4,5 and 6

---

README.md

Hello @Cadair and @nabobalis, I fixed the empty requirements text. Thank you :)

Fixed the empty requirements text

---

team.rst

Fix my affiliation

---

about.rst

- SunPy > sunpy where it is referencing the package
- A couple of typos

Copy check about page

---

project/affiliated.rst

Fixes #221
Fixes #222
Fixes #220
Fixes #225
Fixes #219
Fixes #223
Fixes sunpy/sunpy#4184

Add affiliated packages to page

---

posts/2020/2020-06-03_hdee_sunpy.rst

Let me know what you think about this.

Added a short note about the HDEE sunpy proposal

---

posts/2020/2020-06-12-20_released.rst

Needs to wait for the release to be finished

Add release post for 2.0

---

posts/2020/2020-08-17_affiliated_packages.rst

Here's a first draft of a blog about the new process of becoming a SunPy affiliated package.
Let me know if this is the type of thing we were thinking about @drsophiemurray ?

Affiliated package blog

---

project/affiliated.rst

Revert "update aiapy tests to be excellent"

---

README.md
conf.py
posts/2020/2020-01-10-11_released.rst
posts/2020/2020-06-03_hdee_sunpy.md
posts/2020/2020-08-17_affiliated_packages.rst

I have updated the readme with the new styles for blogposts and changed existing ones to make sure it works. 
Fixes #251

markdown and rst check

---

project/index.rst

* Added links to four board meetings to reflect [SunPy Wiki](https://github.com/sunpy/sunpy/wiki/Home%3A-Organization-Information)
* Updated board members to reflect [SEP-006](https://github.com/sunpy/sunpy-SEP/blob/master/SEP-0006.md)

Updated board meeting notes + board members

---

chat.html
conf.py

Add a chat redirect

---

index.rst

Update what's new link for 3.0 release

---

.pre-commit-config.yaml
conf.py
requirements.txt

https://www.opengraph.xyz/url/https:%2F%2Fdeploy-preview-268--sunpy.netlify.app%2F/

test with master theme

---

about.rst

This adds Monica's 2020 scipy talk to the carousel

Add scipy 2020 sunpy talk

---

project/index.rst

Removed @mbobra as docs maintainer

Removed @mbobra as docs maintainer

---

index.rst

Small consistency edit, since sunpy 3.0 is the package (not the project)

SunPy > sunpy

---

posts/2021/2021-10-08_nasa_osftl_grant.rst

I don't really know what else to put in here @ayshih / @wtbarnes thoughts?
https://deploy-preview-278--sunpy.netlify.app/posts/2021/2021-10-08_nasa_osftl_grant

An OSTFL Grant announcement post

---

project/roles.rst

Add me as release manager

---

posts/2022/2022-01-06-aiapy-demo.ipynb

Fix author list in aiapy blog post

---

conf.py

Point release config variable at "main" branch

---

binder/requirements.txt

This is for the aiapy blogpost

Add aiapy to binder dependencies 

---

.github/ISSUE_TEMPLATE/reevaluation_affiliated_package.md

Fixes #242
Will need heavy reworking.

reevaluation of affiliated packages template

---

project/meetings.rst

* Add map
* Add hotel recommendations

Update 2022 coordination meeting page

---

index.rst

Don't merge this until readthedocs finishes building 4.0

Update home page to 4.0

---

project/index.rst
project/meetings.rst

Adds a first draft of an agenda for the 2022 coordination meeting. Please edit/suggest as needed or if you want to remove your name from anything.

Add agenda for 2022 coordination meeting

---

project/meetings.rst

Fixes https://github.com/sunpy/sunpy.org/issues/310
Fixes https://github.com/sunpy/sunpy.org/issues/309

30 min blocks

---

project/meetings.rst

Add a section that says all participants must abide by the SunPy Code of Conduct

Add a CoC for the 2022 meeting

---

project/meetings.rst

The link to register for the coordination meeting was broken

Fix registration link

---

project/meetings.rst

Add youtube and chat links for coord meeting

---

project/affiliated.rst

This makes the affiliated package lists more compact.

Move links to description lines for affiliated packages

---

README.md
project/affiliated.rst
project/index.rst
project/roles.rst

I noticed a few small typos as mentioned in #325. This pull request corrects those.

corrects small typos

---

project/affiliated.rst

Fixes https://github.com/sunpy/sunpy.org/issues/273

Add sunpy-soar as an affiliated package

---

conf.py
requirements.txt

See what the new ablog means for us.

ablog==0.11.0rc1

---

project/index.rst
project/roles.rst

Fixes https://github.com/sunpy/sunpy.org/issues/187

Added it all back

---

conf.py
exts/cards.py
help.md
project/index.rst
requirements.txt

As suggested by @jmbhughes at the coordination meeting, this should simplify and improve the help page

Improve help page

---

.gitignore
Makefile
conf.py
index.rst
project/affiliated.rst
tox.ini

Add roentgen to affiliated package list
Fixes https://github.com/sunpy/sunpy.org/issues/335 as well
Fixes https://github.com/sunpy/sunpy.org/issues/331 as well
Fixes https://github.com/sunpy/sunpy.org/issues/322 as well - Minus the nice graphics.

Add roentgen to affiliated package list

---

project/affiliated.rst
project/index.rst
project/roles.rst

Also a couple of package maintainer roles that I don't have time for any more

Remove myself from release manager role

---

project/affiliated.rst

A set of very minor changes, to make the descriptions of affiliated packages easier to read.

Minor improvements to affiliated package descriptions

---

index.rst

**don't merge until readthedocs catches up with stable**

Update version on index

---

index.rst

Update links for new docs

---

affiliated.rst

As per the review in #373 
@wtbarnes I took your comment about the codecov bage to mean I could bump the tests to excellent. Let me know if you disagree.

Add DKIST package to affiliated package page

---

help.md

Fixed broken link to chat

---

home.html

We know that working on code and submitting pull requests takes effort, and we appreciate your time.
Thank you.
[Please be aware that everyone has to follow our code of conduct](https://sunpy.org/coc)
[Furthermore, you might need to check with your work place if you are allowed to contribute code](https://docs.sunpy.org/en/latest/dev_guide/contents/newcomers.html)
- Please try to create an issue _before_ creating a Pull Request.
- Please use the following Git commit message style
- Use the future tense ("Adds feature" not "Added feature")
- Limit the first line to 72 characters or less
We have several automatic features that run when a pull request is open.
They can appear daunting but do not worry about them!
[This a brief explanation of …

Update home.html to show 5.1

---

affiliated.rst

Added missing comma

---

affiliated.rst

Add `solarmach` to affiliated package list

---

affiliated.rst
posts/2013/2013-07-21-sunpy-at-scipy.rst

updated soar doc link

---

posts/2024/2024-04-03-eclipse.ipynb

Makes a bit more sense than taking the average over the 2nd axis.

Use rgb2gray to make image grayscale

---

posts/2024/2024-04-03-eclipse.ipynb
posts/2024/eclipse_helpers.py

* Refactored away the dependency on `photutils`
* Fixed the x/y confusion and polished some of the plotting
* Extracted the GPS altitude from the EXIF metadata
* Fixed the conflation of the lunar disk and the solar disk
The angular offset of Regulus matches better, but is still not great.  However, we don't know how much lens distortion there is

Various fixes to the eclipse notebook

---

about/meetings.rst

Adding some details about the coordination meeting in June

Adding coord meeting info to webpage

---

about/index.rst
about/project.rst

More tweaks to project page

---

about/coordination_meet_2025.rst
about/meetings.rst

Small fixes about the room and modifies "here" links to descriptive ones.

Fixes to rooms and here links for Sunpy Coordination meeting 2025

---

about/project.rst

Noticed that I am missing in the list of Project Custodians, so here is the addition.

Update Project Custodians

---

affiliated.rst

Add `scope` as an affiliated package
